//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_Dictionary
    {
        public System.Guid ID { get; set; }
        public string sText { get; set; }
        public int iValue { get; set; }
        public string sValueType { get; set; }
        public int iOrder { get; set; }
        public bool bIsDeleted { get; set; }
    }
}
